### ISSUE TITLE
Nota doesn't receive file system notifications when workspace folders move

### ISSUE THREAD

**Issue by lolbat** [notaapp/nota#100]
Nota doesn't appear to get file system notifications from the OS when a workspace folder is moved or renamed.

**Comment by astoilkov** [comment]
Yes. We don't have access to the APIs macOS provides for tracking moving and renaming done outside of Nota. However, we can detect if you renamed the workspace and kept it in the same folder. We also can search for the moved folder one/two levels up or down to try and find it.

Can you describe your use case so we can figure out if we will be able to cover it? Do you rename/move often? When moving a folder where do you move it relative to its original location?

Thanks in advance!

**Comment by lolbat** [comment]
I do not rename or move very much. In this case I moved some directories around to rearrange a project since I had the docs, data and application code in different places. All the various items I needed were in three different places so I consolidated them and it involved moving the documentation directory. 

It isn't something that I will be doing often. :-)

I think that it would be useful if Nota failed better though. When it couldn't find the workspace it actually gave me a dialog saying that I didn't have any and asked me to open a new one. I actually freaked out a bit as I thought it had lost all of my workspaces.

It had only misplaced the one I moved though so perhaps a new dialog saying that Nota couldn't find the Workspace and ask the user to either find it or remove it from the app?

**Comment by astoilkov** [comment]
> I think that it would be useful if Nota failed better though. When it couldn't find the workspace it actually gave me a dialog saying that I didn't have any and asked me to open a new one. I actually freaked out a bit as I thought it had lost all of my workspaces.

Aha, yes, it feels like this can be stressful.

> It had only misplaced the one I moved though so perhaps a new dialog saying that Nota couldn't find the Workspace and ask the user to either find it or remove it from the app?

I like the idea. Thanks for the feedback and the idea.
