### ISSUE TITLE
System autocorrect & Text Replacement — MacOS

### ISSUE THREAD

**Issue by Auratelience** [notaapp/nota#103]
Adding support for the MacOS Dictionaries and text replacement would be incredible. Mainly the dictionaries to give support to Australian / British spellings.

**Comment by astoilkov** [comment]
HI @Auratelience,

We use the native macOS spellchecking implementation. Nota should work the same way other macOS apps work. Are you experiencing something else?

We are currently exploring text replacements. You can see thread https://github.com/notaapp/nota/discussions/89 for more information.

**Comment by Auratelience** [comment]
#89: Would be good to have.
Reinstalling Nota with the update version and a restart has fixed the problem. It's probably because I'm running macOS Monterey.
