### ISSUE TITLE
Bug? Custom Command + iCloud File

### ISSUE THREAD

**Issue by Scribilicious** [notaapp/nota#109]
I get the follow error when using a custom command in combination with files from stored on my iCloud:
<img width="255" alt="Screenshot 2021-09-24 at 22 27 37" src="https://user-images.githubusercontent.com/4229679/134735934-0e6b0526-f20b-4baa-a8fd-79c098c9292a.png">
Followed by:
<img width="254" alt="Screenshot 2021-09-24 at 22 31 17" src="https://user-images.githubusercontent.com/4229679/134736314-f7b01774-f595-4ec0-80ca-aaa76a732c7b.png">
If I user files directly from Documents I don't get this error. The script I'm using is:
```

#!/bin/bash
# @parameters file
open -a "Marked 2" $1$2

```

**Comment by astoilkov** [comment]
Can you try the modified script below? The path to your document contains spaces and the script interprets the spaces like different arguments. This is why I added quotes around the parameter in my modification.
```
#!/bin/bash
# @parameters file
open -a "Marked 2" "$1"
```

**Comment by Scribilicious** [comment]
Aha! Thanks :) That works!
