### ISSUE TITLE
Tab characters

### ISSUE THREAD

**Issue by astoilkov** [notaapp/nota#11]
Nota doesn't support tab characters for now. We understand this is quite a controversial decision. This is why we created this issue – to collect feedback and explain our reasoning.

These are the reasons we haven't implemented tab characters yet:
- **It's hard to implement.** Every character in the editor has the same width regardless of where is inside the text but the tab character width varies – always depending on the width of the previous characters. This requirement will make the codebase more complex and it will take time to implement.
- **Tab character can be 1px.** Because of the nature of the tab character, it is possible to end with a 1px tab character which won't look good if you have two letters between the tab.
- **Tab character can be replaced with tables.** Tabs are often used for creating tables. We would prefer to spend the time saved in not implementing tabs into world-class table support. Tabs seem inferior to tables because they are hard to maintain – extra tabs should be added/removed when changing the length of words.

If you have an opinion on the matter please write in this thread.

**Comment by mrbbp** [comment]
tab characters are useless in a md/web flux.
page design with tab characters is bad job.
md file are not suppose to support that... therefor don't do.
i use nota to write not to make graphic design!

**Comment by astoilkov** [comment]
I am closing this issue as we've made multiple improvements to tabs.
