### ISSUE TITLE
Default keyboard shortcuts persist and override changes

### ISSUE THREAD

**Issue by Clock-Drift** [notaapp/nota#112]
When changing keyboard shortcuts for commands the change is (1) not reflected in the pop-up menu and (2) prevents using default shortcut patterns for different shortcuts (e.g. 'Go to Heading' - changed to `cmd+shift+H` but still set as `cmd+shift+O` in the pop up menu as well as preventing changing other shortcuts to that sequence).

(1)
<img width="501" alt="Screenshot 2021-09-25 at 14 36 25" src="https://user-images.githubusercontent.com/48359410/134773447-606f6b66-bbaa-4df5-91ec-e454adb0e0d1.png">

<img width="379" alt="Screenshot 2021-09-25 at 14 36 32" src="https://user-images.githubusercontent.com/48359410/134773450-8961ebb6-56cd-46d8-9a5f-9c64ffb82cfc.png">

(2)
<img width="372" alt="Screenshot 2021-09-25 at 14 38 56" src="https://user-images.githubusercontent.com/48359410/134773549-5712d680-f21f-4c00-87f3-354dde1368ff.png">

**Comment by astoilkov** [comment]
Thanks for reporting. We will fix both of these soon.

The second issue is wrongly showing an alert. However, when I tested it, the new custom shortcut worked.

**Comment by astoilkov** [comment]
This should be fixed in the latest 0.34 update.

@Clock-Drift Can you verify that?

I am closing this issue. If something is still not working correctly I will immediately reopen it. Thanks for the bug report!
