### ISSUE TITLE
Feature Request: Down arrow moves to end of line

### ISSUE THREAD

**Issue by owenfiscus** [notaapp/nota#119]
Many editors allow you to jump to the end of the line you are currently on quickly by hitting the down arrow key. I find myself attempting this in Nota due to muscle memory and would love to see it added. Thanks!

**Comment by astoilkov** [comment]
Wow. That's actually a bug (regression) that was introduced in the last release and we didn't notice. We already fixed it so the next release will include it.

Thank you very much for reporting this.

**Comment by astoilkov** [comment]
This is now fixed in the latest 0.34 update.

Closing this issue. Thanks for reporting!
