### ISSUE TITLE
Sometimes note does not open when triggering via CLI

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/nota#126]
I have an Alfred workflow that creates an empty markdown file with today's date for a diary entry, triggered by an Alfred keyword.
I then let Nota open it so I can add  the diary entry to the file.
Sometimes the note does not open in Nota though.

My observations:

- It's not reproducible when it does not show
- I suspected for some time that it does not show when nota was already open before, but sometimes it still works
- Another idea I had is that nota does not have the note indexed quick enough (there is some notable lag between creating a note outside of Nota when using iDrive/Dropbox/normal file system), but I cannot prove or disprove that

Any ideas or things I could try out to narrow down the problem?

Here's the technical details:

1. Append to file via Alfred, if exists, append
2. Write `# {var:today}` to file
3. Terminal command: `nota {var:folder}/{var:today}.md`

I'm using Nota Version 0.33.0 (Intel)

**Comment by astoilkov** [comment]
I think I figured out what is happening. The next release will include the fix for this issue.

**Comment by astoilkov** [comment]
This should be fixed in the latest 0.34 update.

I am closing this issue.
