### ISSUE TITLE
Some wiki links not working

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/nota#127]
Sometimes (and I could not find a pattern yet), the autocompletion for a wiki link breaks the link after `[[`. When I manually remove the line break, the link looks right but actually creates a fresh markdown file.

See here: https://www.loom.com/share/183a58c73a7c4692809964f3db52b960

**Comment by astoilkov** [comment]
Hmm. Strange. I went through the code and couldn't figure why this could be happening. A few questions:
- You are giving an example with the file "21-10-07-Bad Schöneberg". Do you always observe this behavior when trying to link to "21-10-07-Bad Schöneberg"?
- I see two problems in the video. Having an additional line break and ⌘+click not opening the file. Can one happen without the other?
- How often does this happen?

Thanks in advance!

**Comment by minthemiddle** [comment]
>     * You are giving an example with the file "21-10-07-Bad Schöneberg". Do you always observe this behavior when trying to link to "21-10-07-Bad Schöneberg"?

Yes, tried it in different notes on different machines and always fails.

> 
>     * I see two problems in the video. Having an additional line break and ⌘+click not opening the file. Can one happen without the other?

I could produce an error where I don't get a line break but the file does not open still.
I think it is related to the special characters (German umlaute)

- I created a new file with special character name `21-11-09-Können`
- I linked with with wiki links
- The link looks okay
- When I click on the link, a new file gets produced

> 
>     * How often does this happen?

I feel it has to do with special characters (see above). I could not observe it for other files yet.

> 
> 
> Thanks in advance!

**Comment by astoilkov** [comment]
Thanks! I successfully replicated the issue. However, interestingly, I replicated it in a Dropbox folder but not outside of Dropbox. Is your folder inside of Dropbox by any chance?

**Comment by minthemiddle** [comment]
@astoilkov Yes, I'm using it inside of Dropbox

**Comment by astoilkov** [comment]
I will need more time to understand why this is happening only inside of Dropbox. I already have a fix but I would like to understand the problem first.

Thanks!

**Comment by astoilkov** [comment]
@minthemiddle I fixed the problem and the next release will include the fix. However, while fixing it I believe Dropbox fixed the issue themselves. If you want you can test if you still have the same problem.

**Comment by minthemiddle** [comment]
Just tested it and it still takes up to 15 seconds that Nota picks up the newly created file. Can surely check again with the new release.

**Comment by astoilkov** [comment]
@minthemiddle This issue is not the performance one. It's the one that wiki-link don't work when they contain German umlaute.

**Comment by minthemiddle** [comment]
> @minthemiddle This issue is not the performance one. It's the one that wiki-link don't work when they contain German umlaute.

Sorry, checked the Umlaute again and yes, it works and the Github fix seems to be sufficient.
