### ISSUE TITLE
Feature Request: Copy wiki link on right click

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/nota#128]
- Right now you can create wiki links by typing `[[` in every note and picking a file from the list
- When you right click a file in the file browser, you can only copy the full path link via `Copy`
- It would be great to be able to copy wiki links via right click in the file browser as well
- Use case: I often browse files visually and want to link them in another file

**Comment by astoilkov** [comment]
I like the idea but we want less clutter in the context menu and we will probably make this possible through extensibility. What do you think about dragging and dropping the link? We currently create a normal Markdown link when dragging and dropping but we are working on an option that will insert wiki-link instead.

**Comment by minthemiddle** [comment]
@astoilkov Oh dragging and dropping would work perfectly fine. And I understand that reducing or preventing clutter is a top prio.

**Comment by astoilkov** [comment]
Great. Toggling the setting I am talking about will also make the Copy command paste the link like a wiki-link in the editor.

**Comment by astoilkov** [comment]
Now we have a new Preferences → Workspace → Use Wiki links option that will paste a wiki-link if you copy a file from the FileBar.

Do you think this is enough or do you think we should do more about this?

**Comment by minthemiddle** [comment]
@astoilkov Just tried it out now. This fully solves my issue. Thanks!
