### ISSUE TITLE
Externally created notes take long to show up in Nota (in a 6k+ library)

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/nota#129]
When I create an external note (in my case via Alfred), saving to Dropbox, it takes many seconds (10s+) until it shows up in Nota. 

I also tried it on non-cloud (Mac native files), it is also slow, but I could not compare the times it took.

https://www.loom.com/share/2ecdc3571bbb4a8580c53dc45647f36b

**Comment by astoilkov** [comment]
Yes. This is caused by the fact that you have a workspace with over 6 thousand files. We still haven't optimized for the use case where you have a big workspace and you are frequently creating files outside of it. We should do something about this.

Thanks.

**Comment by astoilkov** [comment]
One quick question. Do you have an easy way to count how many folders you have inside of your workspace? I'm asking because the performance depends more on the number of folders and not so much on the number of files.

**Comment by minthemiddle** [comment]
- Folders: 190
- Files: 8000

**Comment by minthemiddle** [comment]
> Yes. This is caused by the fact that you have a workspace with over 6 thousand files. We still haven't optimized for the use case where you have a big workspace and you are frequently creating files outside of it. We should do something about this.

I could imagine that all folders and files are being watched (as in `tail -f`). Within my library, only a small amount of folders change frequently (for me namely the monthly folders and Zettelkasten folders). I could imagine that setting priority folders to watch (and respond quickly) would work and help in my case.

**Comment by astoilkov** [comment]
> Folders: 190

Folders are not a lot. I will create more test workspaces to explore the issue.

> I could imagine that all folders and files are being watched (comparably to tail -f). Within my library, only a small amount of folders change frequently (for me namely the monthly folders and Zettelkasten folders). I could imagine that setting priority folders to watch (and respond quickly) would work and help in my case.

Yes. I was thinking about a similar solution.

**Comment by astoilkov** [comment]
We improved the code related to updating the workspace. The change will be included in the next release.

Now it should be at least 10-30 times faster.

@minthemiddle I want to thank you for all the issues you have spent time writing us. We appreciate it a lot!

**Comment by astoilkov** [comment]
@minthemiddle This should be fixed in 0.34.0. Can you test to confirm that?

**Comment by minthemiddle** [comment]
@astoilkov Yes, it's a lot faster. I close the ticket.
