### ISSUE TITLE
Create new notes quickly

### ISSUE THREAD

**Issue by Overload119** [notaapp/nota#13]
In a single directory I want to type `[[` and then along with other docs the first result should be "Create new..."

So typing [[MyDoc]] will create a new file MyDoc.md in the current folder of the file I'm in.

**Comment by astoilkov** [comment]
The next version will fully support wiki-links and then you would be able to do:
- write [[folder/doc]]
- Cmd+Click the link or hit Ctrl+Enter and it will prompt you to create that file

Do you think this will be good enough?

**Comment by Overload119** [comment]
Will have to try it and see :)

**Comment by astoilkov** [comment]
We implemented the suggestion that you made. You can ⌘-click or choose to create a new file from the dropdown. We hope you like it.

@Overload119 Is the current behavior the way you imagined it?

**Comment by astoilkov** [comment]
Closing this issue. @Overload119, if you have more suggestions for this workflow you can write here and I will reopen the issue.
