### ISSUE TITLE
Dark mode preview

### ISSUE THREAD

**Issue by Auratelience** [notaapp/nota#130]
Just got blinded viewing the preview at night using dark mode.
Otherwise this application is excellent and I am purchasing a licence when I get home.

**Comment by astoilkov** [comment]
> Otherwise this application is excellent and I am purchasing a licence when I get home.

Thanks for the kind words. I hope you enjoy Nota as much as we are enjoying building it.

> Just got blinded viewing the preview at night using dark mode.

This is a duplicate. You can follow https://github.com/notaapp/nota/issues/30. I am closing this so other people don't get confused.
