### ISSUE TITLE
Clicking on a item link in the preview opens an editor, instead of within nota

### ISSUE THREAD

**Issue by dvcrn** [notaapp/nota#136]
1. Create 2 files
2. Create a `[[backlink]]` in one to the other file
3. Activate preview and click on the backlink

Should: Open the other markdown file within nota

Does: Opens whatever is associated with that filetype. So in my case it opens xcode for .md files

**Comment by astoilkov** [comment]
This is a bug. We fixed it and the next release will include the fix. Thanks!

**Comment by astoilkov** [comment]
This is now fixed in the latest 0.34 update.

Thanks for the report!

Closing this issue.
