### ISSUE TITLE
Strange list pasting behavior

### ISSUE THREAD

**Issue by borekb** [notaapp/nota#138]
I've got this text in my clipboard:

```
Group A:
1. A1
2. A2
3. A3
Group B:
1. B1
2. B2
3. B3
```

If I paste this into an empty document in Nota, it works well:

![Screen Shot 2021-12-17 at 14 13 58](https://user-images.githubusercontent.com/101152/146549946-84a9de6f-a92f-483e-ae58-99bd299e9580.png)

As soon as the file contains any other text, pasting changes the numbers in the "Group B":

![Screen Shot 2021-12-17 at 14 14 46](https://user-images.githubusercontent.com/101152/146550042-be11c87a-65eb-453d-982a-7278bc4801ec.png)

I don't seem to be able to paste the text as-is in this latter case.

**Comment by astoilkov** [comment]
Yes, this is a bug. We've already fixed it for the next release.

**Comment by astoilkov** [comment]
This is now fixed in the 0.34 update.

Closing this issue. Thanks for reporting, Borek!
