### ISSUE TITLE
Link and Fill Title pastes title in the wrong place.

### ISSUE THREAD

**Issue by dmbfm** [notaapp/nota#145]
When using the "Link and Fill Title", the title gets placed in the wrong place, outside the link, while the link stays with "loading..." as the title. 

<img width="651" alt="image" src="https://user-images.githubusercontent.com/8743306/151824926-eb7a19a4-f3de-47dc-aaa5-c70fa9c97c02.png">

I'm using version 0.33.0.

**Comment by astoilkov** [comment]
We are aware of the issue and have fixed it. The next release will include the fix. I can write here when it's available.

**Comment by dmbfm** [comment]
Perfect, thanks!

**Comment by astoilkov** [comment]
The fix is now available in the latest 0.34 update.

I am closing this issue. Thanks for reporting!
