### ISSUE TITLE
[0.34.0] Root folder not settable as "Inbox folder"

### ISSUE THREAD

**Issue by dvcrn** [notaapp/nota#150]
I like the new Inbox folder feature, but it doesn't let me set the root folder:

<img width="313" alt="Screen Shot 2022-02-03 at 16 33 16" src="https://user-images.githubusercontent.com/688326/152300468-3f109d93-5563-4ffa-831d-4d591c1a3741.png">

Setting root folder will just keep the dropdown as "Not set"

**Comment by astoilkov** [comment]
Sorry, we will fix this and release a patch version soon.

**Comment by astoilkov** [comment]
This is now fixed and 0.34.1 is release. A notification for the update should show soon. Thanks for reporting!

BTW, you can experiment with the new way of creating notes and if you have any feedback we can continue the discussionin https://github.com/notaapp/nota/issues/137.

**Comment by dvcrn** [comment]
Works now! 👍
