### ISSUE TITLE
Feature Request: Export to HTML

### ISSUE THREAD

**Issue by davistech** [notaapp/nota#152]
I write content for my website using Markdown and constantly need to convert the content to HTML. Most of the other editors that I use, like _Multimarkdown Composer_, support this with **export-to** and **copy-as** functions. _Marked_ also supports conversion but this requires an extra step in my workflow.

**Comment by astoilkov** [comment]
Can `Copy as HTML` command work for you?

We can also possibly add support for Export to HTML in the future.

**Comment by davistech** [comment]
> On Feb 8, 2022, at 5:09 AM, Antonio Stoilkov ***@***.***> wrote:
> 
> 
> Can Copy as HTML command work for you?
> 
> 
This would be great. I don’t need the head section, just the conversion to HTML. There are a lot of ways to do this manually but it would be more efficient to have it available in Nota. This would be particularly helpful since I’m using Nota with Obsidian and it would allow me to convert Obsidian files also.

Thanks.
