### ISSUE TITLE
Feature Request: Show symlinked folders

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/nota#177]
It would be nice if symlinked folders would show up in Nota.

My use case:

- I have folders for my monthly Zettelkasten notes, e.g. `21-02`
- I want to see this month's folder on first level (instead of `Zettelkasten > 2021 > 21-02`)
- I want to use a symlink from the deep folder to the root symlinked folder

An alternative:
- Favourites: Mark a note or folder as favourite and show in a virtual folder `Favourites` (iaWriter has this)
- Saved searches: Add a hashtag `favourite`, save the search for this tag `tag:favourites` as a virtual folder (MailMate has this)

**Comment by astoilkov** [comment]
I was successful at doing this by executing the `ln -s` command in the Terminal: `ln -s ~/Dropbox/Nota/Zettelkasten/2021/21-02/ ~/Dropbox/Nota/`. Have you tried this?

**Comment by minthemiddle** [comment]
@astoilkov Thanks, `ln -s` worked as expected. I think I only tried Mac OS's copy'n'paste link before.
