### ISSUE TITLE
Feature Request: Hide specific folders

### ISSUE THREAD

**Issue by minthemiddle** [notaapp/nota#178]
It would be nice to hide specific folders from Nota's folder view.

My use case:
I have a folder that holds bibliography data (`*.bib`) that I reference in my Nota notes (via `@authorYY`) and later translate to full references with pandoc. The folder holds no info for Nota but I need it to have proper path/content relation to my notes.

Idea:
Folders that start with underscore are hidden, `_bib`

Alternative:
Have a `.nota` config file in the folder to be hidden that holds a key/value of `hidden=1`

**Comment by astoilkov** [comment]
Currently, there are two ways to achieve this. Rename the folder to start `.` or do `git init` and add a `.gitignore` file. Does any of these work for you?

**Comment by minthemiddle** [comment]
`.` format works perfectly.
