### ISSUE TITLE
Open images in external app

### ISSUE THREAD

**Issue by Overload119** [notaapp/nota#20]
Similar functionality as Caret - gives more flexibility in viewing images.

Right now, images open in Nota which doesn't work well for large images.

https://streamable.com/ujlvk7

**Comment by astoilkov** [comment]
We have been thinking about this problem as well. We definitely need to do something so the user can see images bigger or/and zoom. We have two options for now(I will add yours as a third):
- support zooming in and out when an image is opened in a tab
- open images in fullscreen(in Nota) so you can see them better
- and yours – open images in an external app

**Comment by astoilkov** [comment]
In the new release today, we changed the viewing experience for images. Now (when double-clicked), images show as an overlay and take a lot more space. In the next releases, we will make it possible to zoom them by doing a pinch gesture.

@Overload119 Any thoughts on the changes?

**Comment by astoilkov** [comment]
You can now also do Right-Click → Open with Default Program.

I am closing this. If you think we should do more about this, you can write here and I will reopen the thread.
