### ISSUE TITLE
Feature request: Full width image preview and url in editor

### ISSUE THREAD

**Issue by akoliyot** [notaapp/nota#40]
Currently images shows up as a small block in the editor.

![issue_current](https://user-images.githubusercontent.com/8660142/105636319-2678e900-5e68-11eb-9134-bf1184e03780.png)

---

Would it be possible to get it showing like Caret did?
- Image width matches text width.
- Path is shown underneath the image.

![issue_wish](https://user-images.githubusercontent.com/8660142/105636342-3f819a00-5e68-11eb-90dc-cbb971daf4c9.png)

**Comment by astoilkov** [comment]
Hi Aswin,

Let me first explain why we made those changes:
- Images are now thumbnails
  - our users were hitting scenarios where very high images were taking huge amounts of space
  - there is a Preview command where you can see the entire image, the editor is more of a place to edit your text and the Preview is more about seeing the final result
  - other products that display images also use thumbnails, we wanted to be more aligned
- We now hide image paths
  - markdown image syntax is hard to process visually with all those special symbols, we wanted to improve on that
  - markdown images are rarely edited, in most cases, you would replace the image and not edit its path
  - again, other products hide the image path

However, we are open to discussing it and possibly adding customization options. Would you share why do you think the old behavior is better?

Thanks!

**Comment by akoliyot** [comment]
Hey Antonio, thanks for the clear response :)

> Images are now thumbnails 

Yeah, I agree most other products seems to do a thumbnail preview too (or only display the image path). It's a personal preference I'd say. I liked the experience of seeing my images in full while I'm writing too.

> We now hide image paths 

I had a very specific use case, but you make some valid points and I understand why it was removed.

**Comment by astoilkov** [comment]
I will leave this thread open so other users can see it and contribute to the discussion.

> I had a very specific use case, but you make some valid points and I understand why it was removed.

If you wish you can share your specific case. It will help us understand the topic better. Also, it can be more popular than you think.

**Comment by akoliyot** [comment]
> I had a very specific use case

It was gonna be my first step in preparing cards for Anki. Sometimes I take screenshots of certain things that I want to practise further. So I'll have an image and certain notes that I take, and if I can see the image name right there, it's easy for me to know which one it is and add it to Anki later.

Better yet I think would be if I could just select the image and copy from Nota to Anki.

I hope that's clear, or if not, feel free to ask me more questions!

**Comment by rb81** [comment]
I vote full-width images. Not a fan of the thumbnails. No practical reason, just an aesthetic preference.

**Comment by chrisjcameron** [comment]
For me, being able to look at the image (data plots) while I write about it is essential. With nota's mini-preview, I need to use one app for writing and one for looking at the graphic while I write. With MacDown, I can view the preview pane while writing so it keeps it to a single app. Nota's single pane editor with preview toggle does not support this single-app workflow. 

It would be great if preview size could be set in preferences or if the preview itself could be dragged to resize (or if there was a toggle for small/full width on the preview.

**Comment by lucasnantonio** [comment]
Similar case here, I add images in order to analyze them, so seeing them bigger is essential to my workflow. This could be a settings toggle.

**Comment by erusev** [comment]
Thank you all so much for sharing your thoughts on this 🙏 

We'll try to add a config option (in Editor preferences) that controls the max image height of images (measured in lines). Setting it to a larger value would result in images using the full width of the editor.

**Comment by astoilkov** [comment]
We implemented an option called "Image Height" available in Preferences (⌘,). One of the values is "Full Size" which will make the image always take the full width of the editor.

Thank you all for the feedback!

Closing this thread.
