### ISSUE TITLE
Bug: Save As HuD displaying limited number of folders

### ISSUE THREAD

**Issue by diethardsteiner** [notaapp/nota#49]
When I create a new file and try to save it, the *Save As* HuD displays only a limited number of folders, maybe 15-20. I have at least twice the number in my workspace.
I've got the latest version installed, MacOS.

**Comment by astoilkov** [comment]
@diethardsteiner Can you answer a few questions so we can figure out what's happening?
- Are these folders visible in the folder bar?
- Are these folders starting with a dot: `.folder`?
- Are these folders ignored by git?

**Comment by diethardsteiner** [comment]
the folders are all visible in the folder bar, none of them is a hidden folder and they are all version controlled by git (well, at least the files within them).

**Comment by astoilkov** [comment]
I am asking the last question because we intentionally truncate the initial list of folders and only show the folders if you search/type for them.

**Comment by diethardsteiner** [comment]
ok, I see now. I wanted to add it too root and search for `root` but in fact I should have used `/`. I just checked, other folders do show up in the search result (that do not show up in the list). So actually it is working as you expected. Please close the ticket.

**Comment by astoilkov** [comment]
Actually, your confusion makes a good point for improvement here. We can do a few things:
- searching for "root" to show the `/` root folder
- showing at the end of the lists there are more folders that aren't shown
- showing more folders

Thanks for the feedback.

**Comment by diethardsteiner** [comment]
Yes, these sound like good improvements to me! Thanks.

**Comment by astoilkov** [comment]
Great. As we are happy with those improvements I will close this issue now.

Thank you for helping us improve Nota!
