### ISSUE TITLE
Global keyboard shortcuts

### ISSUE THREAD

**Issue by mikeozornin** [notaapp/nota#51]
Environment:
Nota: Version 0.23.1 (Intel)
macOS: 11.2.3 (20D91)
HW: MacBook Pro (Retina, 15-inch, Mid 2015)

Nota uses hidden global keyboards shortcuts.
E.g:
I have my Nota app opened in background.
I have my Git app opened and focused. 
I pressed ⌘ + ⌥ + O to open finder with repo folder.

I expect:
Finder opened with repo folder (it's a keyboard shortcut for open in finder in my git app).

I got:
Nota goes to foreground and do nothing. I couldn't find such keyboard shortcut

**Comment by astoilkov** [comment]
Do you mean ⌘ + ⌃ + O (Control not Option ⌥)?  We have ⌘ + ⌃ + O as a global shortcut to show Nota. We should definitely make it customizable to avoid such cases.

Sorry for the inconvenience and thanks for the feedback.

**Comment by mikeozornin** [comment]
Yep, ⌘ + ⌃ + O, that's right.

I could remove it by myself, but didn't found in preferences here:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/1744928/111068746-dd4e2880-84eb-11eb-8be4-cbb77bf2f011.png">

**Comment by astoilkov** [comment]
Yes. It's not in Preferences. That's the problem. We will include it as part of the Preferences in a future version.

**Comment by astoilkov** [comment]
In the latest 0.34 update, the shortcut is customizable through Preferences → Shortcuts.

Thanks for the feedback!

Closing this issue.
