### ISSUE TITLE
Feature Request: Add Copy Path as Command

### ISSUE THREAD

**Issue by Overload119** [notaapp/nota#61]
![image](https://user-images.githubusercontent.com/1012072/121759433-7df7b880-cada-11eb-9ddc-46c20d68d56a.png)

I was expecting to see "Copy File Path" as a command here which will copy the path of the current tab.

Also, right clicking the file can present the path there (similar to Sublime Text) but not as necessary. 

![ScreenGrab 2021-06-11 at 17 29 19](https://user-images.githubusercontent.com/1012072/121759451-936ce280-cada-11eb-89cd-db09487953ac.png)

**Comment by astoilkov** [comment]
That's a perfect candidate for a [custom command](https://nota.md/docs/custom-commands.html). Even the getting started example does this. At some point, we will introduce a way to add context menu commands as well.

**Comment by erusev** [comment]
@Overload119 

As a workaround, you can ⌥⌘C on the file in the file manager to get its path.

This is consistent w/ how Finder works.

**Comment by erusev** [comment]
Shipped in 0.30 🚀
