### ISSUE TITLE
Bug / Feature Request - Persistance of state for ToDo items from preview

### ISSUE THREAD

**Issue by joshua-russell** [notaapp/nota#64]
Todo items which are checked while preview is toggled do not remain checked after returning from preview. This would seem to be unexpected behavior. 
![ToDoCheckboxes](https://user-images.githubusercontent.com/2198793/121971624-28741380-cd47-11eb-8d92-1cd2c9dcd82b.gif)

**Comment by astoilkov** [comment]
We implemented this. It will be included in the next release.

BTW, it was more like a feature rather than a bug because it needed a custom implementation in order to work.

Thank you for taking the time and writing to us. Your feedback helps a lot.

**Comment by astoilkov** [comment]
I am closing this issue as it is already available in a Nota public release.
