### ISSUE TITLE
Vim support

### ISSUE THREAD

**Issue by nikitavoloboev** [notaapp/nota#68]
I'd love to be able to use vim bindings to move around.

**Comment by astoilkov** [comment]
Makes sense. Do you currently use another app that has vim bindings?

**Comment by nikitavoloboev** [comment]
Yes, I use [Sublime Text](https://www.sublimetext.com) with with [Six Vim Plugin](https://github.com/guillermooo/Six).

**Comment by astoilkov** [comment]
Cool. Thanks!

Is Vim support blocking you from experimenting with Nota more?

Do you have an extra plugin in Sublime Text adding functionality related to note-taking?

I hope you don't mind asking questions. 🙏

**Comment by nikitavoloboev** [comment]
> Is Vim support blocking you from experimenting with Nota more?

Yes it's a big blocker.

> Do you have an extra plugin in Sublime Text adding functionality related to note-taking?

No, I do have [Alfred plugin to search notes and few little things](https://github.com/nikitavoloboev/small-workflows) thus Nota is potentially a very interesting replacement to my setup.

But yes, vim plugin is an issue for me.

**Comment by astoilkov** [comment]
Thanks! I will post any updates we have on this here.

**Comment by led** [comment]
+1 for vim support
