### ISSUE TITLE
Highlighting doesn't format correctly in Preview

### ISSUE THREAD

**Issue by roligithuban** [notaapp/nota#74]
When I highlight text with ==highlight==, the raw markdown shows a colored highlight but previewing the markdown doesn't show any color highlight and leaves the ""==" signs in place. Copying the markdown into other editors displays the markdown output correctly, however.

**Comment by astoilkov** [comment]
We fixed the issue. The next release will include the fix. Thanks for reporting!

**Comment by astoilkov** [comment]
This is now fixed.

Closing this issue.

Thanks for reporting it.
