### ISSUE TITLE
'View -> Toggle Preview' menu does not toggle

### ISSUE THREAD

**Issue by led** [notaapp/nota#75]
### DESCRIPTION:

`View -> Toggle Preview` does not act as a toggle. Selecting the menu item switches to preview, but selecting again whilst in preview mode does not switch back to edit mode.

### EXPECTED:

Selecting `View -> Toggle Preview` toggles between editor and preview states

### POSSIBLE SOLUTIONS:

- Change the menu text to something like 'Display Preview' to match the current behaviour
- Change the behaviour to actually toggle state
- Revisit when/if the preview pane can be shown alongside the editor pane

**Comment by astoilkov** [comment]
This is a bug. We changed the behavior to actually toggle state. The next release will include the fix.

Thank you!

**Comment by astoilkov** [comment]
This is now fixed.

Thanks for reporting.

Closing this issue.
