### ISSUE TITLE
Palettes (Go To Heading, Go To Backlink) can appear clipped

### ISSUE THREAD

**Issue by led** [notaapp/nota#77]
### DESCRIPTION:
If there's not enough width in the edit window, bringing up the `Go To Heading` or `Go To Backlink` palettes results in them being clipped.

![Napkin 23-06-21, 10 20 08 am](https://user-images.githubusercontent.com/395440/123071477-96d26900-d40c-11eb-84c5-6a8177dcf8eb.png)

### EXPECTED:
The palette isn't clipped.

### POSSIBLE SOLUTIONS:
- Overlay the palette across the workspace in the same way the `Search` palette does.
- Adjust the width as appropriate to the editor width.

**Comment by led** [comment]
To add to this, the `File -> Move To` palette also clips in the same way.

**Comment by astoilkov** [comment]
We fixed the bug. The next release will include the fix. Thanks!

**Comment by astoilkov** [comment]
This is now fixed.

@led Thank you for all the issues that you created. It was extremely valuable.

Closing this issue.
