### ISSUE TITLE
Menu Items for tabs enabled when there are no tabs

### ISSUE THREAD

**Issue by led** [notaapp/nota#79]
### DESCRIPTION:
The `Window -> *tab-related-entries*` are enabled even when there are no tabs.

![Screenshot 2021-06-23 at 11 42 44](https://user-images.githubusercontent.com/395440/123083865-6bee1200-d418-11eb-885f-7afa36139079.png)

### EXPECTED:
Menu items would be disabled when there are no tabs present.

**Comment by astoilkov** [comment]
We fixed the issue. The next release will include the fix. Thanks!

**Comment by astoilkov** [comment]
We improved the behavior of menu items and their state — both in the menu and in the context menu that opens when you right-click on a tab.

Closing this issue.
