### ISSUE TITLE
command line opening

### ISSUE THREAD

**Issue by led** [notaapp/nota#83]
### DESCRIPTION:
Opening a directory or a file _only_ works if the directory is a recognised workspace. If the file or directory is _not_ a workspace then Nota is brought to the foreground but no directory or files from the command line are editable. No message regarding the action not being completed is displayed.

### EXPECTED:
I  expected that `nota \<filename\>` would open the file for editing and `nota \<directory\> would open the directory as a workspace (perhaps symlinking/aliasing if necessary). If nota is unable to open the dir/file then a message would be displayed.

### POSSIBLE SOLUTIONS:
If the current directory (or directory containing the filename) is _not_ a workspace, ask the user if they would like to import it as a workspace then open up the directory or file as appropriate.

**Comment by astoilkov** [comment]
Hmm. I can't replicate the problem. What do you mean by "directory or files from the command line are editable"? Files are opened but can't be edited or just Nota does nothing (it's just brought to the foreground)?

- Can you try running `open -a "Nota" path-to-file-or-directory` and see if the same behavior persists?
- Can you send us the commands that you are executing that don't work?

Note that files that aren't `.md` files won't be opened.

**Comment by led** [comment]
> What do you mean by "directory or files from the command line are editable"? Files are opened but can't be edited or just Nota does nothing (it's just brought to the foreground)?

I've narrowed things down a bit more, so here's an updated description of the issue…

If Nota is _not_ running, then using the command-line `nota arg…` command appears to work as expected. Nota is opened and the appropriate file or directory is ready to work on.

However, if Nota is currently _open_, then nothing happens. If passing a directory as an argument, it is not opened as a workspace. Likewise, a filename as an argument doesn't open the file.

In both cases, the Nota app appears to simply be foregrounded, but there is no change in edit workspace or file.

> Can you try running open -a "Nota" path-to-file-or-directory and see if the same behavior persists?

The behaviour appears the same.

> Can you send us the commands that you are executing that don't work?

Nothing unusual really…

`> nota Van\ Things.md`
`> nota scotland\ trip/`

**Comment by astoilkov** [comment]
Ok. Got it. One last question: On what macOS version are you?

We still can't replicate the problem so we will try to research possible reasons for the bug. I have some ideas.

**Comment by led** [comment]
MacOS Catalina 10.15.7

Let me know if there's anything this end I can do to narrow it down.

**Comment by led** [comment]
Can confirm the issue remains with Nota v0.30.0

**Comment by astoilkov** [comment]
Yep. We've made an effort to fix this but we got blocked by one of our dependencies. We will need to wait for them.

**Comment by astoilkov** [comment]
I think I found the reason why this is happening. The next release will include the potential fix. I will let you know once the release goes public.
