### ISSUE TITLE
Not able to delete notes located in NAS smb share

### ISSUE THREAD

**Issue by kaisarmaytham** [notaapp/nota#91]
Currently running a Synology NAS at home and have my Nota workspace located there.

I am using a Macbook Air M1 (macOS 11.4) to connect to the smb share. Deleting notes from within the Nota application won't work and i resolve to deleting the files manually in Finder. Creating af workspace locally on my Macbook Air seems to solve the issue.

I am able to create notes but aren't able to delete them through the app. Also applies to folder.

**Comment by astoilkov** [comment]
Hmm. We will take a look at this. Thanks for letting us know!

**Comment by jhildenbiddle** [comment]
I can also confirm this is issue. 

https://user-images.githubusercontent.com/442527/153291190-58365d37-b3f0-400a-b471-88656680e52d.mp4

**Comment by astoilkov** [comment]
We fixed this issue and now support this. The 0.35 release will include the change.

**Comment by jhildenbiddle** [comment]
That's great, @astoilkov. Looking  forward to it. Thanks for the quick reply.

**Comment by astoilkov** [comment]
This is now fixed in the latest 0.34 update.

Thanks for reporting!

Closing this issue.
