### ISSUE TITLE
WYSIWYG: formatting chars not copied

### ISSUE THREAD

**Issue by borekb** [notaapp/nota#92]
Step to reproduce:

1. Create a new file, go to the experimental WYSIWYG mode
2. Write the word "test"
3. Make it bold
4. Select all (Cmd-A)
5. Copy (Cmd-C)

In the clipboard, the first two `**` are missing, in other words, this is selected (which can be viewed by pressing Option-Cmd-W):

<img width="197" alt="Screen Shot 2021-08-08 at 7 22 15-shadow" src="https://user-images.githubusercontent.com/101152/128621777-77fe5573-8a97-4f45-a590-e0aab0416438.png">

**Comment by astoilkov** [comment]
Awesome. Thanks for reporting. This helps a lot!

**Comment by astoilkov** [comment]
This is now fixed in the latest release. Thanks for reporting Borek.
