### ISSUE TITLE
WYSWYG: Formatted text + `()`

### ISSUE THREAD

**Issue by dsdeur** [notaapp/nota#93]
I've found a small bug in the WYSIWYG editor mode. 
When you have bold/italic/strikethrough text and add `()` around it, it will not parse the bold/italic/strikethrough, see the screen recording for an example: 

https://user-images.githubusercontent.com/372756/129017600-4b552a56-44be-4be5-b88e-d1741b66ebbd.mov

Highlighting does not seem to have this issue, also different types of brackets do work as I would expect.
I don't think it's very important, also easy to work around, but thought it might be helpful to know.

P.S. Great work on Nota, I use it daily for pretty much all my notes, it's really good! 🙌

**Comment by astoilkov** [comment]
We changed the way WYSIWYG and now this bug doesn't exist. Thanks for reporting!

@dsdeur quick question: What do you think about the new WYSIWYG design called Hide Markdown?

**Comment by dsdeur** [comment]
Awesome! Works great, thanks.

I like it, it makes sense! I couldn't find it at first after it changed, but that's because I was looking specifically for `WYSIWYG`, but I was looking in the right place. The name is very on point imo, hiding markdown is exactly what it does. 

I really like that mode, perfect combination of efficient writing/editing with markdown while not having the "noise" when reading. I have it always enabled.

**Comment by astoilkov** [comment]
Amazing! Thanks for the feedback. If you have any other feedback or ideas for us — we are always available.

Closing this issue now.
