### ISSUE TITLE
Support for piped links

### ISSUE THREAD

**Issue by jeroenpardon** [notaapp/nota#95]
I recently discovered Nota. It has a lot of potential, keep up the great work!

One thing that is stopping me from commiting to it is the lack of support for piped wiki links.

Example: 

`[[Foo|Bar]]`

Would result in linking to the note _Foo_, but _Bar_ is used as the link text.

**Comment by astoilkov** [comment]
Hi, thanks for the idea.

Where do you want to see the link text? Are you using another system that transforms your Markdown?

Do you want support for wiki-links labels in Preview?

**Comment by jeroenpardon** [comment]
Yes, I use a Gatsby based site. That already transforms the markdown to html with support for piped links, so I have that end covered. But I would like to see it work within the Nota editor. I want it mainly so I can fit links better in multiple scenarios. 

For example I might have a note titled "Graphic design", but in a different note I want to incorporate a link i a sentence like "I am a graphic designer", where I want "graphic designer" to open the note "graphic design". It would save me from having to forcefully change sentences to make the words "fit" ;) 

Hope that makes it more clear

**Comment by astoilkov** [comment]
Yes, it all makes sense. Thanks. Do you use a specific plugin for Gatsby or does Gatsby supports this by default?

**Comment by jeroenpardon** [comment]
Cool. I'm using this plugin: https://www.gatsbyjs.com/plugins/gatsby-remark-obsidian. It's a plugin created to work with Obsidian, but it's not an Obsidian specific feature, Wikipedia for instance supports piped links as well: https://en.wikipedia.org/wiki/Wikipedia:Piped_link

**Comment by astoilkov** [comment]
Great. Thanks for all the details.

**Comment by astoilkov** [comment]
This feature is now available in the latest 0.34 update.

Thanks for the idea!
