### ISSUE TITLE
Crtl-B not working as a hotkey for Backlinks?

### ISSUE THREAD

**Issue by Overload119** [notaapp/nota#97]
![ScreenGrab 2021-08-25 at 11 04 31](https://user-images.githubusercontent.com/1012072/130843135-78feca7f-6186-41fc-8710-4cd3faa0d55e.png)

https://user-images.githubusercontent.com/1012072/130843238-51158e04-22b9-421a-88c0-caf99804ed0b.mp4

Instead it seems to just backspace.

**Comment by astoilkov** [comment]
I fixed the issue. The next release will include the fix. Thank you for reporting it.

**Comment by astoilkov** [comment]
The fix is part of the release that we published today.

Closing this issue.
