### ISSUE TITLE
Copying and pasting headings from one Nota document to the other

### ISSUE THREAD

**Issue by lolbat** [notaapp/nota#98]
I have one document that had a block of text in it that I copied from one Nota file to another.

The first line of text was an H4 heading element.

When I pasted it the \#### tags didn't appear but the text kept the styling from the first document. If I add the markdown tags manually they just appear in the document as text and don't turn the line into a heading element. When you preview it the \#### elements are visible in the preview

**Comment by astoilkov** [comment]
How did you select the text? Using drag or via Select All (⌘A)?

When typing the #### do you have space between the # symbols and the text — `#### heading`?

Thanks!

**Comment by lolbat** [comment]
I can't reproduce it now. I had to remove the entire paragraph when it showed up but right now when I try to replicate it I can't. I'll go back to the original documents and see if I can find a series of reproducible steps

**Comment by lolbat** [comment]
Still haven't been able to reproduce it so lets just label it as PEBKAC :-)

**Comment by astoilkov** [comment]
😃 Ok.

BTW, thanks for all the issues and feedback. This is extremely helpful. You can even contact me directly at hello@astoilkov.com if you want to chat or have some wishes for the app.
