### ISSUE TITLE
Ordered list + move line up/down breaks numbering

### ISSUE THREAD

**Issue by nianiam** [notaapp/nota#99]
If I have:

1. Test 1
2. Test 2

Then try to re-order the list by **either** moving 'Test 1' down or 'Test 2' up, the new list will look like:

2. Test 2
3. Test 1

Continuing to do so will keep on increasing the numbers. Perhaps list items should be aware of the maximum list number and also the number of adjacent list items.

**Comment by astoilkov** [comment]
We will fix this soon. Thanks for reporting!

**Comment by astoilkov** [comment]
I fixed the issue. The next release will include the fix. Thanks for reporting @nianiam!

**Comment by astoilkov** [comment]
The fix is part of the release that we published today.

Thank you for reporting.

Closing this issue.
